import = ["~/.config/alacritty/themes/themes/kanagawa_dragon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8

decorations = "buttonless"

# opacity = 0.9
# blur = true

option_as_alt = "Both"

[font]
size = 19
normal.family = "FiraCode Nerd Font"

[[keyboard.bindings]]
key = "J"
mods = "Control"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "K"
mods = "Control"
action = "ScrollHalfPageUp"
